name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: docker build -t my_trading_client .

    - name: Run tests in Docker container
      run: |
        docker run --rm \
          -e BINANCE_TESTNET_API_KEY="${{ secrets.BINANCE_TESTNET_API_KEY }}" \
          -e BINANCE_TESTNET_KEY_PASSWORD="${{ secrets.BINANCE_TESTNET_KEY_PASSWORD }}" \
          -e BYBIT_TESTNET_API_KEY="${{ secrets.BYBIT_TESTNET_API_KEY }}" \
          -e BYBIT_TESTNET_API_SECRET="${{ secrets.BYBIT_TESTNET_API_SECRET }}" \
          my_trading_client